services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run dev
    container_name: bookkinder-frontend-dev
    networks:
      - bookkinder-network

networks:
  bookkinder-network:
    driver: bridge