apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: bookkinder
data:
  VITE_API_BASE_URL: "http://bookkinder.local/api"
  NODE_ENV: "production"
  PORT: "3000"
  HOST: "0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: bookkinder
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bookkinder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: bookkinder-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: frontend-config

